// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOvqbmSaihnnTeoewdJPoy-86NT92W2wQ',
    appId: '1:520758704933:web:40a93f9a2eb983bd3bb8cc',
    messagingSenderId: '520758704933',
    projectId: 'al-hasanain-a7472',
    authDomain: 'al-hasanain-a7472.firebaseapp.com',
    storageBucket: 'al-hasanain-a7472.firebasestorage.app',
    measurementId: 'G-78QH9G7SCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy3QlCa5w9lEVNIOv5Dt2ZjyCZCEgn_zk',
    appId: '1:520758704933:android:c1ba364ffccea68a3bb8cc',
    messagingSenderId: '520758704933',
    projectId: 'al-hasanain-a7472',
    storageBucket: 'al-hasanain-a7472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT6ZbuAiSDfIQWJmxFGbwe5hwixe6ne1k',
    appId: '1:520758704933:ios:b1a5cf241042b3313bb8cc',
    messagingSenderId: '520758704933',
    projectId: 'al-hasanain-a7472',
    storageBucket: 'al-hasanain-a7472.firebasestorage.app',
    iosBundleId: 'com.alhasanain.studant.parents.app.alhasanainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT6ZbuAiSDfIQWJmxFGbwe5hwixe6ne1k',
    appId: '1:520758704933:ios:b1a5cf241042b3313bb8cc',
    messagingSenderId: '520758704933',
    projectId: 'al-hasanain-a7472',
    storageBucket: 'al-hasanain-a7472.firebasestorage.app',
    iosBundleId: 'com.alhasanain.studant.parents.app.alhasanainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOvqbmSaihnnTeoewdJPoy-86NT92W2wQ',
    appId: '1:520758704933:web:c18dfd863b57d4143bb8cc',
    messagingSenderId: '520758704933',
    projectId: 'al-hasanain-a7472',
    authDomain: 'al-hasanain-a7472.firebaseapp.com',
    storageBucket: 'al-hasanain-a7472.firebasestorage.app',
    measurementId: 'G-1M1K3K7MY5',
  );
}
